//! `furst-rt`: runtime types for the FurstSharp FFI bridge.
//!
//! This crate is automatically used by code generated by `#[furst_export]`.
//! Consumer crates should not need to interact with these types directly —
//! the macro and codegen handle them transparently.

/// An owned UTF-8 string whose memory is managed by Rust and must be freed
/// by calling [`furst_free_string`] after use on the F# side.
///
/// Memory layout matches a Rust `String` (ptr, len, cap), making
/// conversion zero-cost in both directions.
#[repr(C)]
pub struct FurstStr {
    pub ptr: *mut u8,
    pub len: usize,
    pub cap: usize,
}

// SAFETY: FurstStr is a plain data bag — the pointer it holds is valid until
// furst_free_string is called, and it is never aliased concurrently by the
// generated wrappers.
unsafe impl Send for FurstStr {}
unsafe impl Sync for FurstStr {}

impl From<String> for FurstStr {
    fn from(s: String) -> Self {
        let mut s = std::mem::ManuallyDrop::new(s);
        FurstStr {
            ptr: s.as_mut_ptr(),
            len: s.len(),
            cap: s.capacity(),
        }
    }
}

/// Free a [`FurstStr`] that was returned from a Rust function across the FFI
/// boundary. Must be called exactly once after the F# side is done with the
/// string.
///
/// # Safety
/// `s` must have been produced by a `#[furst_export]` function and not yet
/// freed.
#[no_mangle]
pub extern "C" fn furst_free_string(s: FurstStr) {
    // Reconstruct the original String so Rust's allocator can free it.
    // SAFETY: ptr/len/cap came from a valid String via ManuallyDrop above.
    unsafe {
        drop(String::from_raw_parts(s.ptr, s.len, s.cap));
    }
}
